"""Add disk_filename column to PDFFile

Revision ID: 5011659e3aac
Revises: 524b262ce399
Create Date: 2025-03-04 17:32:37.358962

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5011659e3aac"
down_revision = "524b262ce399"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pdf_files")
    with op.batch_alter_table("pdf_file", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("disk_filename", sa.String(length=255), nullable=False)
        )
        batch_op.alter_column(
            "filename",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pdf_file", schema=None) as batch_op:
        batch_op.alter_column(
            "filename",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=120),
            existing_nullable=False,
        )
        batch_op.drop_column("disk_filename")

    op.create_table(
        "pdf_files",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "filename", sa.VARCHAR(length=120), autoincrement=False, nullable=False
        ),
        sa.Column(
            "upload_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pdf_files_pkey"),
    )
    # ### end Alembic commands ###
