"""Add category to Post

Revision ID: 808e30267346
Revises: 5011659e3aac
Create Date: 2025-03-24 02:04:04.559176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808e30267346'
down_revision = '5011659e3aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
